In [1]:
import numpy as np 
import pandas as pd 
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor

# Data Collection - Train Set

In [2]:
points2014 = pd.read_csv('IPL 2014 PT.csv')
points2015 = pd.read_csv('IPL 2015 PT.csv')
points2016 = pd.read_csv('IPL 2016 PT.csv')
points2017 = pd.read_csv('IPL 2017 PT.csv')
points2018 = pd.read_csv('IPL 2018 PT.csv')
points2019 = pd.read_csv('IPL 2019 PT.csv')
points2019

,Team,Pld,Won,Lost,Tied,N/R,Net RR,For,Against,Pts
0,Mumbai Indians MI,14,9,5,0,0,0.421,"2,380/275.1","2,282/277.2",18
1,Chennai Super Kings CSK,14,9,5,0,0,0.131,"2,043/274.1","2,012/274.5",18
2,Delhi Capitals DC,14,9,5,0,0,0.044,"2,207/272.5","2,238/278.1",18
3,Sunrisers Hyderabad SRH,14,6,8,0,0,0.577,"2,288/269.2","2,200/277.5",12
4,Kolkata Knight Riders KKR,14,6,8,0,0,0.028,"2,466/270.4","2,419/266.2",12
5,Kings XI Punjab KXIP,14,6,8,0,0,-0.251,"2,429/276.3","2,503/277",12
6,Rajasthan Royals RR,14,5,8,0,1,-0.449,"2,153/257","2,192/248.2",11
7,Royal Challengers Bangalore RCB,14,5,8,0,1,-0.607,"2,146/258.4","2,266/254.3",11

In [3]:
point=points2014.append([points2015,points2016,points2018,points2017,points2019])
point.head()

,Team,Pld,Won,Lost,Tied,N/R,Net RR,For,Against,Pts
0,Kings XI Punjab KXIP,14,11,3,0,0,0.968,"2,427/268.3","2,229/276.1",22
1,Kolkata Knight Riders KKR,14,9,5,0,0,0.418,"2,125/264","2,110/276.3",18
2,Chennai Super Kings CSK,14,9,5,0,0,0.385,"2,272/272","2,178/273.2",18
3,Mumbai Indians MI,14,7,7,0,0,0.095,"2,180/271.3","2,170/273.3",14
4,Rajasthan Royals RR,14,7,7,0,0,0.060,"2,155/269.5","2,164/273",14

In [4]:
points = point.groupby('Team').mean()
points

,Pld,Won,Lost,Tied,N/R,Net RR,Pts
Team,,,,,,,
Chennai Super Kings CSK,14.0,9.000000,5.000000,0.0,0.000000,0.369500,18.000000
Delhi Capitals DC,14.0,5.666667,8.166667,0.0,0.166667,-0.346000,11.500000
Gujarat Lions GL,14.0,6.500000,7.500000,0.0,0.000000,-0.393000,13.000000
Kings XI Punjab KXIP,14.0,6.166667,7.833333,0.0,0.000000,-0.312667,12.333333
Kolkata Knight Riders KKR,14.0,7.666667,6.166667,0.0,0.166667,0.229333,15.500000
Mumbai Indians MI,14.0,7.833333,6.166667,0.0,0.000000,0.238000,15.666667
Rajasthan Royals RR,14.0,6.500000,6.750000,0.0,0.750000,-0.144250,13.750000
Rising Pune Supergiant RPS,14.0,7.000000,7.000000,0.0,0.000000,0.095500,14.000000
Royal Challengers Bangalore RCB,14.0,5.666667,7.666667,0.0,0.666667,-0.039333,12.000000
Sunrisers Hyderabad SRH,14.0,7.333333,6.500000,0.0,0.166667,0.177833,14.833333

In [5]:
matches = pd.read_csv('Matches.csv')
match = matches.drop(['city','venue','umpire1','win_by_runs','win_by_wickets','season'],axis=1)
match

,id,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,player_of_match,umpire2,umpire3
0,1,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,Yuvraj Singh,NJ Llong,NaN
1,2,06-04-2017,Mumbai Indians,Rising Pune Supergiants,Rising Pune Supergiants,field,normal,0,Rising Pune Supergiants,SPD Smith,S Ravi,NaN
2,3,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,CA Lynn,CK Nandan,NaN
3,4,08-04-2017,Rising Pune Supergiants,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,GJ Maxwell,C Shamshuddin,NaN
4,5,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,KM Jadhav,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
353,11347,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,HH Pandya,O Nandan,S Ravi
354,11412,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,AS Yadav,Nitin Menon,Ian Gould
355,11413,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,RR Pant,NaN,NaN
356,11414,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,F du Plessis,Bruce Oxenford,Chettithody Shamshuddin
357,11415,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,JJ Bumrah,Ian Gould,Nigel Llong

# Data Preprocessing

In [6]:
def string_remover(df,list1=[],list2=[],drop=[],exclude=[],include=[]):
    a = df.select_dtypes(include='object')
    for i in a.columns:
        list1=[]
        d=0
        if not i in exclude and i in include:
            list1.append(i)
            for x in a.index:
                try:
                    c = list1.index(a[i].iloc[x:x+1][x])
                    a[i].iloc[x:x+1][x] = c
                except:
                    list1.append(a[i].iloc[x:x+1][x])
                    a[i].iloc[x:x+1][x] = len(list1)-1
            list2.append(list1)
            d+=1
    a.fillna(len(list1))
    d = df.select_dtypes(exclude='object').fillna(0)
    try:
        return pd.concat([d,a],axis=1).fillna(0).drop([drop],axis=1)
    except:
        return pd.concat([d,a],axis=1).fillna(0)

In [7]:
match['win']=None
match['toss_win']=None
for i in match.index:
    if match.winner[i] == match.team1[i]:
        match['win'][i] = 'team 1'
    else:
        match['win'][i] = 'team 2'    
    if match.toss_winner[i] == match.team1[i]:
        match['toss_win'][i] = 'team 1'
    else:
        match['toss_win'][i] = 'team 2'

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [8]:
a=[]
b=['toss_decision', 'field', 'bat', 'toss_win', 'team 1', 'team 2']
match

,id,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,player_of_match,umpire2,umpire3,win,toss_win
0,1,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,Yuvraj Singh,NJ Llong,NaN,team 1,team 2
1,2,06-04-2017,Mumbai Indians,Rising Pune Supergiants,Rising Pune Supergiants,field,normal,0,Rising Pune Supergiants,SPD Smith,S Ravi,NaN,team 2,team 2
2,3,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,CA Lynn,CK Nandan,NaN,team 2,team 2
3,4,08-04-2017,Rising Pune Supergiants,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,GJ Maxwell,C Shamshuddin,NaN,team 2,team 2
4,5,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,KM Jadhav,NaN,NaN,team 1,team 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,11347,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,HH Pandya,O Nandan,S Ravi,team 2,team 2
354,11412,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,AS Yadav,Nitin Menon,Ian Gould,team 2,team 1
355,11413,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,RR Pant,NaN,NaN,team 2,team 2
356,11414,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,F du Plessis,Bruce Oxenford,Chettithody Shamshuddin,team 2,team 2
357,11415,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,JJ Bumrah,Ian Gould,Nigel Llong,team 1,team 1

In [9]:
match = string_remover(match,include=['toss_decision','toss_win'],list1=b,list2 = a)
match

,id,dl_applied,date,team1,team2,toss_winner,toss_decision,result,winner,player_of_match,umpire2,umpire3,win,toss_win
0,1,0,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,1,normal,Sunrisers Hyderabad,Yuvraj Singh,NJ Llong,0,team 1,1
1,2,0,06-04-2017,Mumbai Indians,Rising Pune Supergiants,Rising Pune Supergiants,1,normal,Rising Pune Supergiants,SPD Smith,S Ravi,0,team 2,1
2,3,0,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,1,normal,Kolkata Knight Riders,CA Lynn,CK Nandan,0,team 2,1
3,4,0,08-04-2017,Rising Pune Supergiants,Kings XI Punjab,Kings XI Punjab,1,normal,Kings XI Punjab,GJ Maxwell,C Shamshuddin,0,team 2,1
4,5,0,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,2,normal,Royal Challengers Bangalore,KM Jadhav,0,0,team 1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,11347,0,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,1,normal,Mumbai Indians,HH Pandya,O Nandan,S Ravi,team 2,1
354,11412,0,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,2,normal,Mumbai Indians,AS Yadav,Nitin Menon,Ian Gould,team 2,2
355,11413,0,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,1,normal,Delhi Capitals,RR Pant,0,0,team 2,1
356,11414,0,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,1,normal,Chennai Super Kings,F du Plessis,Bruce Oxenford,Chettithody Shamshuddin,team 2,1
357,11415,0,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,2,normal,Mumbai Indians,JJ Bumrah,Ian Gould,Nigel Llong,team 1,2

In [10]:
match['team2'].unique()

array(['Royal Challengers Bangalore', 'Rising Pune Supergiants',
       'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Daredevils',
       'Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rajasthan Royals', 'Chennai Super Kings', 'Delhi Capitals'],
      dtype=object)

In [11]:
points.drop('Tied',inplace=True,axis=1)

In [12]:
points.index = ['Chennai Super Kings', 'Delhi Capitals',
       'Gujarat Lions', 'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians',
       'Rajasthan Royals',
       'Rising Pune Supergiants','Royal Challengers Bangalore',
       'Sunrisers Hyderabad']
points

,Pld,Won,Lost,N/R,Net RR,Pts
Chennai Super Kings,14.0,9.000000,5.000000,0.000000,0.369500,18.000000
Delhi Capitals,14.0,5.666667,8.166667,0.166667,-0.346000,11.500000
Gujarat Lions,14.0,6.500000,7.500000,0.000000,-0.393000,13.000000
Kings XI Punjab,14.0,6.166667,7.833333,0.000000,-0.312667,12.333333
Kolkata Knight Riders,14.0,7.666667,6.166667,0.166667,0.229333,15.500000
Mumbai Indians,14.0,7.833333,6.166667,0.000000,0.238000,15.666667
Rajasthan Royals,14.0,6.500000,6.750000,0.750000,-0.144250,13.750000
Rising Pune Supergiants,14.0,7.000000,7.000000,0.000000,0.095500,14.000000
Royal Challengers Bangalore,14.0,5.666667,7.666667,0.666667,-0.039333,12.000000
Sunrisers Hyderabad,14.0,7.333333,6.500000,0.166667,0.177833,14.833333

In [13]:
points.index.name = 'Team'
for i in [match[match['team2']=='Delhi Daredevils'].index,match[match['team2']=='Pune Warriors'].index]:
    for i in i:
        match.drop(i,inplace=True)
for i in [match[match['team1']=='Delhi Daredevils'].index,match[match['team1']=='Pune Warriors'].index]:
    for i in i:
        match.drop(i,inplace=True)
points.to_csv('IPL_Points_Table.csv')

In [14]:
match['Team1_pts'] = None
match['Team1_RR'] = None
match['Team2_pts'] = None
match['Team2_RR'] = None
for i in match.index:
    match['Team1_pts'][i] = points.Pts[match.team1[i]]
    match['Team1_RR'][i] = points['Net RR'][match.team1[i]]
    match['Team2_pts'][i] = points.Pts[match.team2[i]]
    match['Team2_RR'][i] = points['Net RR'][match.team2[i]]
for i in match.index:
    match['Team2_pts'][i] = points.Pts[match.team2[i]]
    match['Team2_RR'][i] = points['Net RR'][match.team2[i]]

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [15]:
points

,Pld,Won,Lost,N/R,Net RR,Pts
Team,,,,,,
Chennai Super Kings,14.0,9.000000,5.000000,0.000000,0.369500,18.000000
Delhi Capitals,14.0,5.666667,8.166667,0.166667,-0.346000,11.500000
Gujarat Lions,14.0,6.500000,7.500000,0.000000,-0.393000,13.000000
Kings XI Punjab,14.0,6.166667,7.833333,0.000000,-0.312667,12.333333
Kolkata Knight Riders,14.0,7.666667,6.166667,0.166667,0.229333,15.500000
Mumbai Indians,14.0,7.833333,6.166667,0.000000,0.238000,15.666667
Rajasthan Royals,14.0,6.500000,6.750000,0.750000,-0.144250,13.750000
Rising Pune Supergiants,14.0,7.000000,7.000000,0.000000,0.095500,14.000000
Royal Challengers Bangalore,14.0,5.666667,7.666667,0.666667,-0.039333,12.000000
Sunrisers Hyderabad,14.0,7.333333,6.500000,0.166667,0.177833,14.833333

# Predicter() to predict match winner using Random Forest Algorithm

In [16]:
RC = RandomForestClassifier(random_state=0)
match.win = match['win']
#match[['Team1_pts','Team1_RR','Team2_pts','Team2_RR',]]
RC.fit(X=match[['Team1_pts','Team1_RR','Team2_pts','Team2_RR','toss_decision','toss_win']],y=match.win)

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [17]:
def Predicter(team1,team2,toss_winner,toss_decision):
    Team1_pts = points.Pts[team1]
    Team1_RR = points['Net RR'][team1]
    Team2_pts = points.Pts[team2]
    Team2_RR = points['Net RR'][team2]
    pred = RC.predict([[Team1_pts,Team1_RR,Team2_pts,Team2_RR,toss_decision,toss_winner]])
    if pred == 'team 1':
        return team1
    else:
        return team2

In [18]:
Predicter('Chennai Super Kings','Mumbai Indians',toss_decision=1,toss_winner=2)

'Mumbai Indians'

# Data Collection - Test Set

In [19]:
ipl_20 = pd.read_csv('Matches IPL 2020.csv')
ipl_20.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1216492,2020,Abu Dhabi,09/19/2020,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,5,AT Rayudu,"Sheikh Zayed Stadium, Abu Dhabi",Chris Gaffaney,Virender Sharma,Sundaram Ravi
1,1216493,2020,Dubai (DSC),09/20/2020,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,tie,0,Delhi Capitals,0,0,MP Stoinis,Dubai International Cricket Stadium,Anil Chaudhary,Nitin Menon,Paul Reiffel
2,1216534,2020,Dubai (DSC),09/21/2020,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,field,normal,0,Royal Challengers Bangalore,10,0,YS Chahal,Dubai International Cricket Stadium,Anil Dandekar,Nitin Menon,Anil Chaudhary
3,1216496,2020,Sharjah,09/22/2020,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Rajasthan Royals,16,0,SV Samson,Sharjah Cricket Stadium,Chettithody Shamshuddin,Vineet Kulkarni,KN Ananthapadmanabhan
4,1216508,2020,Abu Dhabi,09/23/2020,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,field,normal,0,Mumbai Indians,49,0,RG Sharma,"Sheikh Zayed Stadium, Abu Dhabi",Chris Gaffaney,Sundaram Ravi,Virender Sharma

In [20]:
ipl_20=ipl_20.drop(['id','season','city','date','venue','umpire1','umpire2','umpire3','win_by_runs','win_by_wickets','result','dl_applied','player_of_match'],axis=1)
ipl_20.head()

,team1,team2,toss_winner,toss_decision,winner
0,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings
1,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals
2,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,field,Royal Challengers Bangalore
3,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,field,Rajasthan Royals
4,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,field,Mumbai Indians

# Data Preprocessing

In [21]:
ipl_20['win']=None
ipl_20['toss_win']=None
for i in ipl_20.index:
    if ipl_20.winner[i] == ipl_20.team1[i]:
        ipl_20['win'][i] = 'team 1'
    else:
        ipl_20['win'][i] = 'team 2'    
    if ipl_20.toss_winner[i] == ipl_20.team1[i]:
        ipl_20['toss_win'][i] = 'team 1'
    else:
        ipl_20['toss_win'][i] = 'team 2'  
ipl_20.head()

,team1,team2,toss_winner,toss_decision,winner,win,toss_win
0,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,team 2,team 2
1,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals,team 1,team 2
2,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,field,Royal Challengers Bangalore,team 2,team 1
3,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,field,Rajasthan Royals,team 1,team 2
4,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,field,Mumbai Indians,team 2,team 1

In [22]:
a=[]
b=['toss_decision', 'field', 'bat', 'toss_win', 'team 1', 'team 2']
ipl_20 = string_remover(ipl_20,include=['toss_decision','toss_winner'],list1=b,list2 = a)
ipl_20['predict_win']=None
ipl_20.head()

,team1,team2,toss_winner,toss_decision,winner,win,toss_win,predict_win
0,Mumbai Indians,Chennai Super Kings,1,1,Chennai Super Kings,team 2,team 2,None
1,Delhi Capitals,Kings XI Punjab,2,1,Delhi Capitals,team 1,team 2,None
2,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,Royal Challengers Bangalore,team 2,team 1,None
3,Rajasthan Royals,Chennai Super Kings,1,1,Rajasthan Royals,team 1,team 2,None
4,Kolkata Knight Riders,Mumbai Indians,4,1,Mumbai Indians,team 2,team 1,None

In [23]:
ipl_20.iloc[0,0]

'Mumbai Indians'

# Predicting the IPL 2020 data based on the ML Model

In [24]:
Predicter(ipl_20.iloc[0,0],ipl_20.iloc[0,1],ipl_20.iloc[0,3],ipl_20.iloc[0,2])

'Mumbai Indians'

In [25]:
for i in range(60):
    ipl_20['predict_win'][i]=Predicter(ipl_20.iloc[i,0],ipl_20.iloc[i,1],ipl_20.iloc[i,3],ipl_20.iloc[i,2])

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Bhumika Jindal\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [26]:
ipl_20

,team1,team2,toss_winner,toss_decision,winner,win,toss_win,predict_win
0,Mumbai Indians,Chennai Super Kings,1,1,Chennai Super Kings,team 2,team 2,Mumbai Indians
1,Delhi Capitals,Kings XI Punjab,2,1,Delhi Capitals,team 1,team 2,Delhi Capitals
2,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,Royal Challengers Bangalore,team 2,team 1,Sunrisers Hyderabad
3,Rajasthan Royals,Chennai Super Kings,1,1,Rajasthan Royals,team 1,team 2,Chennai Super Kings
4,Kolkata Knight Riders,Mumbai Indians,4,1,Mumbai Indians,team 2,team 1,Mumbai Indians
5,Kings XI Punjab,Royal Challengers Bangalore,5,1,Kings XI Punjab,team 1,team 2,Royal Challengers Bangalore
6,Chennai Super Kings,Delhi Capitals,1,1,Delhi Capitals,team 2,team 1,Chennai Super Kings
7,Kolkata Knight Riders,Sunrisers Hyderabad,3,2,Kolkata Knight Riders,team 1,team 2,Sunrisers Hyderabad
8,Rajasthan Royals,Kings XI Punjab,6,1,Rajasthan Royals,team 1,team 1,Kings XI Punjab
9,Royal Challengers Bangalore,Mumbai Indians,7,1,Royal Challengers Bangalore,team 1,team 2,Mumbai Indians
10,Delhi Capitals,Sunrisers Hyderabad,8,1,Sunrisers Hyderabad,team 2,team 1,Delhi Capitals
11,Rajasthan Royals,Kolkata Knight Riders,6,1,Kolkata Knight Riders,team 2,team 1,Rajasthan Royals
12,Kings XI Punjab,Mumbai Indians,2,1,Mumbai Indians,team 2,team 1,Mumbai Indians
13,Chennai Super Kings,Sunrisers Hyderabad,3,2,Sunrisers Hyderabad,team 2,team 2,Chennai Super Kings
14,Royal Challengers Bangalore,Rajasthan Royals,6,2,Royal Challengers Bangalore,team 1,team 2,Rajasthan Royals
15,Delhi Capitals,Kolkata Knight Riders,4,1,Delhi Capitals,team 1,team 2,Kolkata Knight Riders
16,Mumbai Indians,Sunrisers Hyderabad,7,2,Mumbai Indians,team 1,team 1,Mumbai Indians
17,Kings XI Punjab,Chennai Super Kings,2,2,Chennai Super Kings,team 2,team 1,Chennai Super Kings
18,Royal Challengers Bangalore,Delhi Capitals,5,1,Delhi Capitals,team 2,team 1,Delhi Capitals
19,Mumbai Indians,Rajasthan Royals,7,2,Mumbai Indians,team 1,team 1,Rajasthan Royals
20,Kolkata Knight Riders,Chennai Super Kings,4,2,Kolkata Knight Riders,team 1,team 1,Chennai Super Kings
21,Sunrisers Hyderabad,Kings XI Punjab,3,2,Sunrisers Hyderabad,team 1,team 1,Sunrisers Hyderabad
22,Rajasthan Royals,Delhi Capitals,6,1,Delhi Capitals,team 2,team 1,Delhi Capitals
23,Kings XI Punjab,Kolkata Knight Riders,4,2,Kolkata Knight Riders,team 2,team 2,Kolkata Knight Riders
24,Chennai Super Kings,Royal Challengers Bangalore,5,2,Royal Challengers Bangalore,team 2,team 2,Royal Challengers Bangalore
25,Sunrisers Hyderabad,Rajasthan Royals,3,2,Rajasthan Royals,team 2,team 1,Sunrisers Hyderabad
26,Mumbai Indians,Delhi Capitals,8,2,Mumbai Indians,team 1,team 2,Mumbai Indians
27,Royal Challengers Bangalore,Kolkata Knight Riders,5,2,Royal Challengers Bangalore,team 1,team 1,Kolkata Knight Riders
28,Sunrisers Hyderabad,Chennai Super Kings,1,2,Chennai Super Kings,team 2,team 2,Chennai Super Kings
29,Delhi Capitals,Rajasthan Royals,8,2,Delhi Capitals,team 1,team 1,Delhi Capitals
30,Royal Challengers Bangalore,Kings XI Punjab,5,2,Kings XI Punjab,team 2,team 1,Kings XI Punjab
31,Mumbai Indians,Kolkata Knight Riders,4,2,Mumbai Indians,team 1,team 2,Mumbai Indians
32,Rajasthan Royals,Royal Challengers Bangalore,6,2,Royal Challengers Bangalore,team 2,team 1,Rajasthan Royals
33,Delhi Capitals,Chennai Super Kings,1,2,Delhi Capitals,team 1,team 2,Chennai Super Kings
34,Sunrisers Hyderabad,Kolkata Knight Riders,3,1,Kolkata Knight Riders,team 2,team 1,Kolkata Knight Riders
35,Mumbai Indians,Kings XI Punjab,7,2,Kings XI Punjab,team 2,team 1,Mumbai Indians
36,Chennai Super Kings,Rajasthan Royals,1,2,Rajasthan Royals,team 2,team 1,Chennai Super Kings
37,Kings XI Punjab,Delhi Capitals,8,2,Kings XI Punjab,team 1,team 2,Kings XI Punjab
38,Kolkata Knight Riders,Royal Challengers Bangalore,4,2,Royal Challengers Bangalore,team 2,team 1,Royal Challengers Bangalore
39,Rajasthan Royals,Sunrisers Hyderabad,3,1,Sunrisers Hyderabad,team 2,team 2,Sunrisers Hyderabad
40,Chennai Super Kings,Mumbai Indians,7,1,Mumbai Indians,team 2,team 2,Mumbai Indians
41,Kolkata Knight Riders,Delhi Capitals,8,1,Kolkata Knight Riders,team 1,team 2,Delhi Capitals
42,Kings XI Punjab,Sunrisers Hyderabad,3,1,Kings XI Punjab,team 1,team 2,Sunrisers Hyderabad
43,Royal Challengers Bangalore,Chennai Super Kings,5,2,Chennai Super Kings,team 2,team 1,Chennai Super Kings
44,Rajasthan Royals,Mumbai Indians,7,2,Rajasthan Royals,team 1,team 2,Mumbai Indians
45,Kolkata Knight Riders,Kings XI Punjab,2,1,Kings XI Punjab,team 2,team 2,Kolkata Knight Riders
46,Sunrisers Hyderabad,Delhi Capitals,8,1,Sunrisers Hyderabad,team 1,team 2,Delhi Capitals
47,Mumbai Indians,Royal Challengers Bangalore,7,1,Mumbai Indians,team 1,team 1,Mumbai Indians
48,Chennai Super Kings,Kolkata Knight Riders,1,1,Chennai Super Kings,team 1,team 1,Kolkata Knight Riders
49,Kings XI Punjab,Rajasthan Royals,6,1,Rajasthan Royals,team 2,team 2,Kings XI Punjab
50,Delhi Capitals,Mumbai Indians,7,1,Mumbai Indians,team 2,team 2,Delhi Capitals
51,Royal Challengers Bangalore,Sunrisers Hyderabad,3,1,Sunrisers Hyderabad,team 2,team 2,Royal Challengers Bangalore
52,Chennai Super Kings,Kings XI Punjab,1,1,Chennai Super Kings,team 1,team 1,Kings XI Punjab
53,Kolkata Knight Riders,Rajasthan Royals,6,1,Kolkata Knight Riders,team 1,team 2,Rajasthan Royals
54,Delhi Capitals,Royal Challengers Bangalore,8,1,Delhi Capitals,team 1,team 1,Delhi Capitals
55,Sunrisers Hyderabad,Mumbai Indians,3,1,Sunrisers Hyderabad,team 1,team 1,Mumbai Indians
56,Delhi Capitals,Mumbai Indians,8,1,Mumbai Indians,team 2,team 1,Delhi Capitals
57,Royal Challengers Bangalore,Sunrisers Hyderabad,3,1,Sunrisers Hyderabad,team 2,team 2,Royal Challengers Bangalore
58,Delhi Capitals,Sunrisers Hyderabad,8,2,Delhi Capitals,team 1,team 1,Sunrisers Hyderabad
59,Delhi Capitals,Mumbai Indians,8,2,Mumbai Indians,team 2,team 1,Mumbai Indians

In [27]:
'''
c=0
for i in range(60):
    if(ipl_20['winner'][i]==ipl_20['predict_win'][i]):
        c=c+1
c
'''

"\nc=0\nfor i in range(60):\n    if(ipl_20['winner'][i]==ipl_20['predict_win'][i]):\n        c=c+1\nc\n"

# Team Ranking using predicted results of IPL 2020

In [28]:
ipl_20.groupby(by='predict_win').count()
result=ipl_20.groupby(by='predict_win').count().sort_values(by = 'win',ascending=False)
result

,team1,team2,toss_winner,toss_decision,winner,win,toss_win
predict_win,,,,,,,
Mumbai Indians,13,13,13,13,13,13,13
Delhi Capitals,10,10,10,10,10,10,10
Chennai Super Kings,9,9,9,9,9,9,9
Sunrisers Hyderabad,7,7,7,7,7,7,7
Kolkata Knight Riders,6,6,6,6,6,6,6
Kings XI Punjab,5,5,5,5,5,5,5
Rajasthan Royals,5,5,5,5,5,5,5
Royal Challengers Bangalore,5,5,5,5,5,5,5

# Accuracy of ML Ranking with actual IPL Ranking

In [29]:
ml_res=result.index.values
print("Our ML Ranking of Players: ",ml_res)
print()

ipl_res=np.array(['Mumbai Indians', 'Delhi Capitals', 'Sunrisers Hyderabad', 'Royal Challengers Bangalore',
                  'Kolkata Knight Riders','Kings XI Punjab', 'Chennai Super Kings','Rajasthan Royals', ])
print("IPL Ranking of Players: ",ipl_res)
print()

sum=0
n=len(ml_res)
for i in range(n):    
    ind=np.where(ipl_res==ml_res[i])    
    if(i>=ind[0][0]):
        diff=i-ind[0][0]
    else:
        diff=ind[0][0]-i
    sum=sum+(n-diff)*(8-i)
    #sum=sum+(n-diff)
    #print(ml_res[i],": ",n-diff)
ideal=0
for i in range(n): 
    ideal=ideal+n*(8-i)    
acc=sum/ideal;
print("Accuracy of Ranking: ",acc*100,"%")

Our ML Ranking of Players:  ['Mumbai Indians' 'Delhi Capitals' 'Chennai Super Kings'
 'Sunrisers Hyderabad' 'Kolkata Knight Riders' 'Kings XI Punjab'
 'Rajasthan Royals' 'Royal Challengers Bangalore']

IPL Ranking of Players:  ['Mumbai Indians' 'Delhi Capitals' 'Sunrisers Hyderabad'
 'Royal Challengers Bangalore' 'Kolkata Knight Riders' 'Kings XI Punjab'
 'Chennai Super Kings' 'Rajasthan Royals']

Accuracy of Ranking:  87.84722222222221 %

# Accuracy of SNA Ranking w.r.t Ranking by ML Model

In [30]:
sna_res=np.array(['Mumbai Indians', 'Delhi Capitals', 'Sunrisers Hyderabad','Chennai Super Kings',
                  'Royal Challengers Bangalore','Rajasthan Royals','Kings XI Punjab','Kolkata Knight Riders'])
print("Our SNA Ranking of Players: ",sna_res)
print()

ml_res=result.index.values
print("Our ML Ranking of Players: ",ml_res)
print()

sum=0
n=len(sna_res)
for i in range(n):    
    ind=np.where(ml_res==sna_res[i])    
    if(i>=ind[0][0]):
        diff=i-ind[0][0]
    else:
        diff=ind[0][0]-i
    sum=sum+(n-diff)*(8-i)
    #print(sna_res[i],": ",n-diff)
ideal=0
for i in range(n): 
    ideal=ideal+n*(8-i)    
acc=sum/ideal;
print("Accuracy of SNA Ranking w.r.t ML: ",acc*100,"%")

Our SNA Ranking of Players:  ['Mumbai Indians' 'Delhi Capitals' 'Sunrisers Hyderabad'
 'Chennai Super Kings' 'Royal Challengers Bangalore' 'Rajasthan Royals'
 'Kings XI Punjab' 'Kolkata Knight Riders']

Our ML Ranking of Players:  ['Mumbai Indians' 'Delhi Capitals' 'Chennai Super Kings'
 'Sunrisers Hyderabad' 'Kolkata Knight Riders' 'Kings XI Punjab'
 'Rajasthan Royals' 'Royal Challengers Bangalore']

Accuracy of SNA Ranking w.r.t ML:  89.23611111111111 %